name: Deployment pipeline

on:
  push:
    branches:
      - main
    pull_request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip') }}
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint 
      - name: build 
        run: npm run build 
      - name: test
        run: npm run test

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip') }}
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v2
      - name: Bump version and push tag 
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

  webhook_notify:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
    - name: Check if MY_SECRET exists
      run: |
        if [ `echo ${{secrets.DISCORD_WEBHOOK}} | wc -c` -lt 2 ]; then
          echo "The secret \"DISCORD_WEBHOOK\" has not been set."
          echo "Please go to \"Settings > Secrets > Actions\" to create it."
          exit 1
        fi
        
      - name: Discord Webhook Notify
        uses: rjstone/discord-webhook-notify@v1.0.4
        
      - name: Deployed Success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
            details: Deployed Succeeded!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Deployed Failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
            details: Deployed failed! 
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}


    
